### PR TITLE
Update links

### PR DESCRIPTION
**Pull request by man4toman**

### CODE REVIEW

**Comment by JulieKuehl** [comment]
We'd like to remove all the links to the `make.wordpress.org` site for lesson plans. Could you please use `https://github.com/wptrainingteam/introduction-to-css` instead?

The other link to the teacher resources is good, though.

**Comment by man4toman** [comment]
Sure, I'll change this link and create new PR.

**Comment by man4toman** [comment]
@JulieKuehl What about: **Teacher Resources page**
I can't find any repo for this.

**Comment by man4toman** [comment]
Hi @JulieKuehl 
Would you please check the update?

**Comment by JulieKuehl** [comment]
Thank you for your contribution! Your pull request has been merged.

The Teacher Resources will likely remain on the make.wordpress.org site, so that link should be okay.

**Comment by man4toman** [comment]
> The Teacher Resources will likely remain on the make.wordpress.org site, so that link should be okay.

Thanks, I will consider it.

**Pull request merged**
